-- MySQL Script generated by MySQL Workbench
-- Thu Aug  9 23:31:31 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bravi-test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bravi-test` ;

-- -----------------------------------------------------
-- Schema bravi-test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bravi-test` DEFAULT CHARACTER SET utf8 ;
USE `bravi-test` ;

-- -----------------------------------------------------
-- Table `bravi-test`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bravi-test`.`person` ;

CREATE TABLE IF NOT EXISTS `bravi-test`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bravi-test`.`person_contact_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bravi-test`.`person_contact_type` ;

CREATE TABLE IF NOT EXISTS `bravi-test`.`person_contact_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `precedence` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bravi-test`.`person_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bravi-test`.`person_contact` ;

CREATE TABLE IF NOT EXISTS `bravi-test`.`person_contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  `info` VARCHAR(255) NOT NULL,
  `main` TINYINT NOT NULL DEFAULT 0,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_person_contact_person_idx` (`person_id` ASC),
  INDEX `fk_person_contact_person_contact_type1_idx` (`type_id` ASC),
  CONSTRAINT `fk_person_contact_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `bravi-test`.`person` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_contact_person_contact_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `bravi-test`.`person_contact_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bravi-test`.`person`
-- -----------------------------------------------------
START TRANSACTION;
USE `bravi-test`;
INSERT INTO `bravi-test`.`person` (`id`, `name`, `created`) VALUES (DEFAULT, 'Bob Lee', DEFAULT);
INSERT INTO `bravi-test`.`person` (`id`, `name`, `created`) VALUES (DEFAULT, 'Robert Johnson', DEFAULT);
INSERT INTO `bravi-test`.`person` (`id`, `name`, `created`) VALUES (DEFAULT, 'Joe Doe', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `bravi-test`.`person_contact_type`
-- -----------------------------------------------------
START TRANSACTION;
USE `bravi-test`;
INSERT INTO `bravi-test`.`person_contact_type` (`id`, `name`, `precedence`) VALUES (DEFAULT, 'E-mail', 2);
INSERT INTO `bravi-test`.`person_contact_type` (`id`, `name`, `precedence`) VALUES (DEFAULT, 'Celular', 3);
INSERT INTO `bravi-test`.`person_contact_type` (`id`, `name`, `precedence`) VALUES (DEFAULT, 'Telefone Fixo', DEFAULT);
INSERT INTO `bravi-test`.`person_contact_type` (`id`, `name`, `precedence`) VALUES (DEFAULT, 'WhatsApp', 1);
INSERT INTO `bravi-test`.`person_contact_type` (`id`, `name`, `precedence`) VALUES (DEFAULT, 'Skype', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `bravi-test`.`person_contact`
-- -----------------------------------------------------
START TRANSACTION;
USE `bravi-test`;
INSERT INTO `bravi-test`.`person_contact` (`id`, `person_id`, `type_id`, `info`, `main`, `created`) VALUES (DEFAULT, 1, 1, 'my-email@test.com', DEFAULT, NULL);
INSERT INTO `bravi-test`.`person_contact` (`id`, `person_id`, `type_id`, `info`, `main`, `created`) VALUES (DEFAULT, 1, 2, '047 98636-4550', 1, NULL);
INSERT INTO `bravi-test`.`person_contact` (`id`, `person_id`, `type_id`, `info`, `main`, `created`) VALUES (DEFAULT, 2, 1, 'rabbit@hole.deep', 0, NULL);

COMMIT;

