-- MySQL Script generated by MySQL Workbench
-- Tue Aug  7 23:17:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bravi-test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bravi-test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bravi-test` DEFAULT CHARACTER SET utf8 ;
USE `bravi-test` ;

-- -----------------------------------------------------
-- Table `bravi-test`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bravi-test`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bravi-test`.`person_contact_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bravi-test`.`person_contact_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `precedence` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bravi-test`.`person_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bravi-test`.`person_contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `person_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  `main` TINYINT NOT NULL DEFAULT 0,
  `created` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_person_contact_person_idx` (`person_id` ASC),
  INDEX `fk_person_contact_person_contact_type1_idx` (`type_id` ASC),
  CONSTRAINT `fk_person_contact_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `bravi-test`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_contact_person_contact_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `bravi-test`.`person_contact_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
